### ISSUE TITLE
bug in fitFailed condition in fit.cc and fitMPI.cc?

### ISSUE THREAD

**Issue by lan13005** [JeffersonLab/halld_sim#255]
In both programs, the flag to denote a failed fit is given by 

`fitFailed = (fitManager->status() != 0 && fitManager->eMatrixStatus() != 3);
`
Proper convergence occurs when status=0 and eMatrixStatus=3 (look here for the status codes: https://github.com/mashephe/AmpTools/blob/b6ea91d7a78f5d8f1dcb4a2d455d36e3fd54a0d7/AmpTools/IUAmpTools/FitResults.h)  which means the fail condition should be using OR statement rather than an AND statement

**Comment by aaust** [comment]
@lan13005 Is this still an issue?

**Comment by lan13005** [comment]
@aaust yeah it looks like it

**Comment by mashephe** [comment]
It is a bug in the logic -- if someone wants to make a PR, we can merge it.

Matt
