### ISSUE TITLE
The -s and -r options don't work together properly in fitMPI

### ISSUE THREAD

**Issue by denehoffman** [JeffersonLab/halld_sim#282]
Hi all,

I've just been trying some fits where I use MPI, the -r option to run multiple randomized fits, and the -s option to get a seed file output, and I'm getting an unexpected behavior. The fits all converge fine, and fitMPI.cc determines that the 0th iteration has the best likelihood (they're all about the same really). 

`bash
mpirun --mca btl_openib_allow_ib 1 fitMPI -c TMD_no_D1_D0_Dn1.cfg -r 10 -s seed
`
Creates `seed_<iteration>.txt` files for each iteration, and it appears to fill all but the `seed_0.txt` file, and then proceeds to copy this empty file into `seed.txt`. You can see this in the attached screenshot of the directory in which I'm doing the fit:

![image](https://user-images.githubusercontent.com/36977879/228030255-e22d178b-6ebc-445f-b473-2f13b6afd3de.png)

The other seed files are just fine. For instance:

![image](https://user-images.githubusercontent.com/36977879/228030566-56555b79-5fd1-4dd4-a81e-f090ca3c9fcc.png)

I've attached the log file below:

[log_1670515.log](https://github.com/JeffersonLab/halld_sim/files/11081841/log_1670515.log)

# **Note**
The seed file *is* created when running without MPI, and I'm using the latest version of fitMPI in this repository.

**Comment by jrstevenjlab** [comment]
Good catch, it looks like the `ati.fitResult()->writeSeed()` function was getting called before the `ati.finalizeFit()` which I believe leaves your 0th seed file empty and may leave you with an off-by-one counting error in the index of your seed and fit result files.   You should be able to check this is the case if the parameters in your ksks_TMD_0.fit file match those in seed_1.txt

The branch https://github.com/JeffersonLab/halld_sim/tree/mpi_seed_fix has this order corrected.  Can you try that to see if it resolves your issue?

**Comment by denehoffman** [comment]
_It looks like it's half-fixed now? I still have the seed results offset by one (so the fit result from fit 0 appears in seed_1.txt and so on) but it does successfully copy the result from seed_1.txt into seed.txt? Looking over the code, I really can't tell why this is happening, your fix looks like it should have fixed it!_

Edit for posterity: I forgot to rebuild halld_sim...

**Comment by denehoffman** [comment]
Okay, I just checked, it works now

**Comment by denehoffman** [comment]
Oops, didn't mean to close it, I also found that the same thing happens in runParScan, so I've pushed that to your branch as well.

**Comment by denehoffman** [comment]
@jrstevenjlab Oops, didn't mean to close it, I also found that the same thing happens in runParScan, so I've pushed that to your branch as well. Feel free to close this and merge the branch. (Also you might want to check your working branch, I think you added a fix to some amplitude in the same branch, no big deal unless you meant to be doing that on a different one)

**Comment by jrstevenjlab** [comment]
Thanks, I just submitted the PR for others to consider

**Comment by jrstevenjlab** [comment]
closing after merged PR
