### ISSUE TITLE
BreitWigner amplitude introduces a beam energy dependence

### ISSUE THREAD

**Issue by mashephe** [JeffersonLab/halld_sim#316]
Through the course of some studies, it was observed that the scale BreitWigner amplitude has an implicit dependence on the beam energy.  This is most easily seen if one attempts to generate pseudodata using a BW accept/reject algorithm with AmpTools.  This would be commonly done with gen_amp using a config file that has BreitWigner amplitudes.  If one attempts to generate events using the PS flux vs. E to populate the energy distribution then what one obtains in the end is something that is not consistent with PS flux vs E over a broad range.  (@KSaldan can perhaps post some plots here that illustrate the effect.)  The effect is minimized if the MC are generated with a realistic t dependence rather than a phase-space t dependence.  This likely has a minimal effect on analyses that are fitting a narrow region in the coherent peak, but it is important to keep in mind.

I suspect this has to do with how the width enters into the BW function normalization... perhaps the mass-dependent width `width` should be used instead of `m_width0`?  This needs a little testing and checking.  Perhaps we want to remove this since GlueX analyses in general will always have some distribution of beam energies.

**Comment by KSaldan** [comment]
[ftpComp_noBW_P4.pdf](https://github.com/JeffersonLab/halld_sim/files/14512413/ftpComp_noBW_P4.pdf)
[ftpComp_BW_P4.pdf](https://github.com/JeffersonLab/halld_sim/files/14512414/ftpComp_BW_P4.pdf)
[ftpComp_BW_noT_P4.pdf](https://github.com/JeffersonLab/halld_sim/files/14512415/ftpComp_BW_noT_P4.pdf)
Here are some plots that show the beam energy dependence Matt describes.

**Comment by KSaldan** [comment]
This last plot show the average weights to the energy distribution.
[ftpComp_Weights.pdf](https://github.com/JeffersonLab/halld_sim/files/14512483/ftpComp_Weights.pdf)

**Comment by maltealbrecht** [comment]
@KSaldan Whats the difference between "gen_amp" and "gen_amp_V2"? Could you add some explanation to these plots, especially the last set with the weights?

**Comment by KSaldan** [comment]
gen_amp_V2 uses the FixedTargetGenerator class to generate N body phase-space (can check the branch in halld_sim under ksaldan_gen_amp_V2). Each plot uses an AmpTools config file (taken from the GlueX 2022 tutorial) with the reaction beam p eta pi0 with a dynamic BW defined for a2->eta pi0. The first three plots show the implicit dependence the BW amplitude has on the energy under different scenarios. 
The last pdf I plotted the ratio between the energy distribution weighted by the amplitude intensity of the reaction and the unweighted energy distribution, effectively giving me the average weight given in bins of beam energy.  This is plotted for the same scenarios given in the first three plots.

**Comment by mashephe** [comment]
OK, I think I understand this.  There are a lot of variables....  gen_amp_v2 changes the eta pi mass dependence.  This mass dependence will depend on energy because the phase space changes.   So the eta pi mass is sampling different amounts of the eta pi BW function in a way that depends on beam energy.  I suspect when the energy is decreased the phase space peaks closer to the a2 and this causes the rise in the average intensity.  So, I think that my initial statement that the BW has some implicit energy dependence is not correct.... it's a bit more subtle.

The t-dependence is also linked because modifying the t distribution indirectly changes the eta pi mass distribution.

**Comment by maltealbrecht** [comment]
Thank you for the explanations. I agree, its subtle but that means it is important to generate with a more or less correct t-distribution

**Comment by mashephe** [comment]
I'm going to close this issue to avoid distraction....  I thought the root cause was different and more relevant, but I didn't quite devote enough brain cycles to it.
