### ISSUE TITLE
write weight to generated HDDM file

### ISSUE THREAD

**Issue by mashephe** [JeffersonLab/halld_sim#334]
Around line 64 of: 

src/libraries/AMPTOOLS_MCGEN/HDDMDataWriter.cc

one needs to write the weight from the Kinematics class to the reaction structure.  Some generators will generate with weights that are useful at later stages of the analyses and these should  be preserved.  It seems like the HDDM data structure has a field for this, as hddm-xml produces things like:

<physicsEvent eventNo="8" runNo="30496">
    <reaction type="0" weight="0">
    
I think this is a single line operation where one sets the appropriate data member of the reaction structure to  kin.weight()      

...unfortunately after some looking, I'm unable to find the file  HDDM/hddm_s.hpp to try to see how to do this.

**Comment by jrstevenjlab** [comment]
I think you just need to add the line

`rs().setWeight(kin.weight());`

between line 63 and 64 of https://github.com/JeffersonLab/halld_sim/blob/master/src/libraries/AMPTOOLS_MCGEN/HDDMDataWriter.cc

That at least compiled for me, but I didn't test that weights are propagated downstream.

**Comment by rjones30** [comment]
Yes, as Justin says. Here is a slightly more pedagogical answer to the same
question.

Suppose I want to find out if MC events have a "weight" attribute attached
to each simulated event?

   - find any existing simulation file, either from a generator or after
   the simulator, or after mcsmear, any simulation hddm file will do, and do
   "head" to print the first few lines. Yes, the first few lines are ordinary
   text.

***@***.*** ~]$ head  ~halld/HDGeant4/jlab/test/bggen_1k.hddm | grep
> --color=always -e "^" -e "weight"
> <HDDM class="s" version="1.0" xmlns="http://www.gluex.org/hddm">
>   <geometry maxOccurs="1" md5reconstruction="string"
> md5simulation="string" md5smear="string" minOccurs="0" />
>   <physicsEvent eventNo="int" maxOccurs="unbounded" runNo="int">
>     <dataVersionString maxOccurs="unbounded" minOccurs="0" text="string" />
>     <ccdbContext maxOccurs="unbounded" minOccurs="0" text="string" />
>     <reaction maxOccurs="unbounded" minOccurs="0" type="int" weight="float
> ">
>       <beam minOccurs="0" type="Particle_t">
>         <momentum E="float" px="float" py="float" pz="float" />
>         <polarization Px="float" Py="float" Pz="float" minOccurs="0" />
>         <properties charge="int" mass="float" />
>

   - here you see that "weight" is an attribute of the <reaction> tag with
   type float. This means that the hddm_s::reaction class has two helper
   methods, one getWeight() and the other setWeight(float wgt) to serve as
   getter and setter for this attribute of the hddm_s::reaction object for
   each event.

You could also find this information by digging through the header
hddm_s.hpp, but that file has 30,000 lines of c++ so unless you know what
you are looking for, it can be quite exhausting to dig this information out
that way.
-Richard Jones

**Comment by amschertz** [comment]
I implemented Justin's suggestion and it seems to work - the weights make it to the thrown and reconstructed analysis trees, at least.
<img width="470" alt="Screenshot 2024-05-08 at 12 43 46 PM" src="https://github.com/JeffersonLab/halld_sim/assets/32200825/a857dbeb-f89f-40ac-b2b0-6dd7f3ba3bb6">
<img width="470" alt="Screenshot 2024-05-08 at 12 53 13 PM" src="https://github.com/JeffersonLab/halld_sim/assets/32200825/e0ce5031-a31f-4cf5-be00-725908a24757">

**Comment by mashephe** [comment]
Resolved by #336
