### ISSUE TITLE
Extension to HDDM generator level format

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/halld_sim#44]
From Eugene:

It would be good to have a user-defined variable length array field.

**Comment by rjones30** [comment]
Hello Sean,

There are two ways to do this, each one with pluses and minuses.

   1. save the array as a decimal string
   2. save it as a repeated element, as in the example below.

Both of these have been used by GlueX at different times. The advantage of
#1 is you can express the values with explicit precision by limiting the
significant figures, whereas #2 is more efficient if you want the full
precision of float (4 bytes/element) or double (8 bytes/element). These
examples envision an array of individual hit times, but it could be any
type of repeated variable.

method 1, the prototype:
<hitTimes tvalues="string"/>

method 1, example output from hddm-xml:
<hitTimes tvalues="1.667954,-9.385897,..."/>

method 2, the prototype:
<hitTimes>
  <hitTime t="float" minOccurs="1" maxOccurs="unlimited"/>
</hitTimes>

method 2, an example output from hddm-xml:
<hitTimes>
  <hitTime t="1.667954"/>
  <hitTime t="-9.385897"/>
  ...
</hitTimes>

**Comment by sdobbs** [comment]
Thank for the guidance, Richard.  I took a shot at this in the following pull request:
https://github.com/JeffersonLab/halld_recon/pull/148

This opens the door for future generator development...

**Comment by rjones30** [comment]
Sean,

That looks good, it would make it even better to have a string attribute
for "meaning" that might include something about what is stored and the
units, etc. If you put the string in the mother tag rather than the child,
that would avoid a copy of the string being added to every element of
userDataField if it is an array. The purpose here is to stick to one of the
guiding principles behind hddm that the data should be self-describing.

-Richard Jones

**Comment by rjones30** [comment]
PS. Sean, if you add minOccurs="0" maxOccurs="unbounded" to this userData
tag (the outer one, not just the inner one) then you will (a) save space in
output files that do not need any userData by not requiring an empty
element in every event (that is what your current definition does) and also
allow users to add more than one of these array-valued entries.

-Richard
