### ISSUE TITLE
incomplete path in setenv.csh ??

### ISSUE THREAD

**Issue by mashephe** [JeffersonLab/halld_sim#48]
the setenv.csh file that gets created needs to add to the user path $RCDB_HOME.  It adds $RCDB_HOME/bin, but $RCDB_HOME contains rcnd which appears to be required for MCWrapper.  If rcnd is not in the user path, MCWrapper appears to run (no errors) but nothing happens.

**Comment by mashephe** [comment]
Also, I would argue that if hdgeant4 is going to be the default for doing Hall D simulation then then halld_sim package environment setup should set a path to hdgeant4.

**Comment by faustus123** [comment]
Hi,

  I just submitted a pull request to implement this suggestion.


Regards,
-David

-------------------------------------------------------------
David Lawrence Ph.D.
Staff Scientist, Thomas Jefferson National Accelerator Facility
Newport News, VA
davidl@jlab.org<mailto:davidl@jlab.org>
(757) 269-5567 W
(757) 746-6697 C


On Apr 12, 2019, at 2:09 PM, Matthew Shepherd <notifications@github.com<mailto:notifications@github.com>> wrote:


the setenv.csh file that gets created needs to add to the user path $RCDB_HOME. It adds $RCDB_HOME/bin, but $RCDB_HOME contains rcnd which appears to be required for MCWrapper. If rcnd is not in the user path, MCWrapper appears to run (no errors) but nothing happens.
